spring.application.name=orders

# === Static Resources ===
spring.web.resources.static-locations=classpath:/static/

# === Database ===
spring.datasource.url=jdbc:mariadb://100.70.133.122:3306/pos_db
spring.datasource.username=root
spring.datasource.password=123123123
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# === JPA ===
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# === Order API ===
api.order.base-url=https://pos.pages.fm/api/v1/shops/1546758/orders
api.order.api-key=2a6ed8b51a8d4ae49a851d5876b00018
api.order.connect-timeout=10000
api.order.read-timeout=60000
